### ISSUE TITLE
NullPointerException in ModCompat.blockRightClick

### ISSUE THREAD

**Issue by codewarrior0** [modmuss50/FTB-Achievements-Issues#1]
SkyFactory Challenges 1.0.1

```
Description: Ticking block entity

java.lang.RuntimeException: Error while interacting with block mysticalagriculture:draconium_crop[age=7] with null. Method:ACTIVATE_BLOCK_WITH_ITEM  Button:RIGHT_CLICK
	at com.rwtema.extrautils2.tile.TileUse.operate(TileUse.java:289)
	at com.rwtema.extrautils2.tile.TileAdvInteractor.func_73660_a(TileAdvInteractor.java:93)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at me.modmuss50.ftba.modCompat.ModCompat.blockRightClick(ModCompat.java:27)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_768_ModCompat_blockRightClick_RightClickBlock.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1026)
	at com.rwtema.extrautils2.compatibility.BlockCompat.onRightClickBlock(BlockCompat.java:41)
	at com.rwtema.extrautils2.tile.TileUse.operate(TileUse.java:217)
	... 8 more
```

Seems similar to https://github.com/CoFH/Feedback/issues/107 - getting a `null` returned from `RayTracer.retrace`

**Comment by modmuss50** [comment]
Is this reproducible?

**Comment by codewarrior0** [comment]
In a way. It has happened on two different playthroughs. It seems to be sensitive to the position or orientation of the Mechanical User, as I was able to place and configure several of them before finding one that caused this error.

More importantly, the same crash occurs each time I load up the affected world!

**Comment by codewarrior0** [comment]
`RayTracer.retrace()` can return `null` in some cases (as opposed to a RayTraceResult with a `null` blockPos) if it fails to hit a block. I don't know exactly why. It seems to be the case when the ray trace passes through only blocks that can do a collision check (which means no Air blocks) where all of those blocks fail to collide with the ray (returning `null` from `collisionRayTrace()`), which means `World.rayTraceBlocks()` cannot even return the "last uncollidable block" if asked by the `returnLastUncollidableBlock` argument.

Now for some trivia. The original error message has an inaccuracy. It says the block that failed to interact is `mysticalagriculture:draconium_crop[age=7]`, but because the MechUser has already interacted with it, by the time your `blockRightClick` event handler is called, that block is now `mysticalagriculture:draconium_crop[age=0]`. Since it is a younger crop, it has a smaller bounding box - and on top of that, your (indirect) call to `World.rayTraceBlocks()` has different parameters than the one made by ExU, which is how you end up getting a different result.

**Comment by modmuss50** [comment]
Ok, I will try and add some extra null checks. Thanks for looking into it.

**Comment by codewarrior0** [comment]
Repro steps probably look something like this:

- Plant a line of 7 crops in the growing field
- Plant a line of Mech Users next to the crops and set them to "Activate Block"
- Put an 8th crop at the end of the crop line
- Put a Mech User in what would be the 9th crop's spot, so it is pointing down the line of crops
- Set the 8th Mech User to "Activate Block" - should crash here

Or graphically:

```
MMMMMMM
CCCCCCCCM
```

**Comment by modmuss50** [comment]
Fixed in the next version
